export const universeLuxury = {
    "col": 5,
    "row": 10,
    "seats": [
        { seat: "1-A", status: 'Available' },
        { seat: "1-B", status: 'Available' },
        { seat: "1-C", status: 'hide' },
        { seat: "1-D", status: 'Available' },
        { seat: "1-E", status: 'Available' },
        { seat: "2-A", status: 'Available' },
        { seat: "2-B", status: 'Available' },
        { seat: "2-C", status: 'hide' },
        { seat: "2-D", status: 'Available' },
        { seat: "2-E", status: 'Available' },
        { seat: "3-A", status: 'Available' },
        { seat: "3-B", status: 'Available' },
        { seat: "3-C", status: 'hide' },
        { seat: "3-D", status: 'Available' },
        { seat: "3-E", status: 'Available' },
        { seat: "4-A", status: 'Available' },
        { seat: "4-B", status: 'Available' },
        { seat: "4-C", status: 'hide' },
        { seat: "4-D", status: 'Available' },
        { seat: "4-E", status: 'Available' },
        { seat: "5-A", status: 'Available' },
        { seat: "5-B", status: 'Available' },
        { seat: "5-C", status: 'hide' },
        { seat: "5-D", status: 'Available' },
        { seat: "5-E", status: 'Available' },
        { seat: "6-A", status: 'Available' },
        { seat: "6-B", status: 'Available' },
        { seat: "6-C", status: 'hide' },
        { seat: "6-D", status: 'Available' },
        { seat: "6-E", status: 'Available' },
        { seat: "7-A", status: 'Available' },
        { seat: "7-B", status: 'Available' },
        { seat: "7-C", status: 'hide' },
        { seat: "7-D", status: 'Available' },
        { seat: "7-E", status: 'Available' },
        { seat: "8-A", status: 'Available' },
        { seat: "8-B", status: 'Available' },
        { seat: "8-C", status: 'hide' },
        { seat: "8-D", status: 'Available' },
        { seat: "8-E", status: 'Available' },
        { seat: "9-A", status: 'Available' },
        { seat: "9-B", status: 'Available' },
        { seat: "9-C", status: 'hide' },
        { seat: "9-D", status: 'Available' },
        { seat: "9-E", status: 'Available' },
        { seat: "10-A", status: 'Available' },
        { seat: "10-B", status: 'Available' },
        { seat: "10-C", status: 'Available' },
        { seat: "10-D", status: 'Available' },
        { seat: "10-E", status: 'Available' }
    ]
};