export const universeCounty = {
    "col": 4,
    "row": 9,
    "seats": [
        { seat: "1-A", status: 'Available' },
        { seat: "1-B", status: 'Available' },
        { seat: "1-C", status: 'hide' },
        { seat: "1-D", status: 'hide' },
        { seat: "2-A", status: 'Available' },
        { seat: "2-B", status: 'Available' },
        { seat: "2-C", status: 'Available' },
        { seat: "2-D", status: 'hide' },
        { seat: "3-A", status: 'Available' },
        { seat: "3-B", status: 'Available' },
        { seat: "3-C", status: 'Available' },
        { seat: "3-D", status: 'Available' },
        { seat: "4-A", status: 'Available' },
        { seat: "4-B", status: 'Available' },
        { seat: "4-C", status: 'Available' },
        { seat: "4-D", status: 'Available' },
        { seat: "5-A", status: 'Available' },
        { seat: "5-B", status: 'Available' },
        { seat: "5-C", status: 'Available' },
        { seat: "5-D", status: 'Available' },
        { seat: "6-A", status: 'Available' },
        { seat: "6-B", status: 'Available' },
        { seat: "6-C", status: 'Available' },
        { seat: "6-D", status: 'Available' },
    ]
};